// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package adminClassModifyForm

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"encoding/json"
	"fmt"
	"frontend/database/models"
)

func AdminClassModifyForm(class *models.Class, users []*models.User, subjects []string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		usersJSONBytes, _ := json.Marshal(users)
		usersJSON := string(usersJSONBytes)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"class-edit-wrapper\" x-data=\"userManager()\" x-init=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf(`initExisting(%s)`, usersJSON))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/admin/adminClassModifyForm/adminClassModifyForm.templ`, Line: 15, Col: 53}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"bg-white border border-gray-200 rounded-lg shadow-md p-6 space-y-6 animate-fade-in max-w-5xl mx-auto\"><!-- Header --><div class=\"flex items-center justify-between\"><h3 class=\"text-2xl font-semibold text-black tracking-tight\">Editando clase</h3><span class=\"text-sm text-gray-500 italic\">ID: ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(class.Id)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/admin/adminClassModifyForm/adminClassModifyForm.templ`, Line: 23, Col: 60}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span></div><!-- Form --><form id=\"class-edit-form\" hx-post=\"/admin/class/modify/update\" hx-target=\"#class-edit-feedback\" hx-swap=\"innerHTML\" hx-trigger=\"submit\" @submit=\"handleSubmit\" class=\"grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4\"><input type=\"hidden\" name=\"class_id\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(class.Id)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/admin/adminClassModifyForm/adminClassModifyForm.templ`, Line: 35, Col: 56}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"><!-- Nombre --><div class=\"flex flex-col\"><label class=\"text-sm font-medium text-gray-700 mb-1\">Nombre</label> <input type=\"text\" name=\"name\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(class.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/admin/adminClassModifyForm/adminClassModifyForm.templ`, Line: 42, Col: 23}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" required class=\"input input-bordered bg-white border-gray-300 text-black text-sm focus:border-red-600 focus:ring-0\"></div><!-- Asignatura --><div class=\"flex flex-col\"><label class=\"text-sm font-medium text-gray-700 mb-1\">Asignatura</label> <select name=\"subject\" required class=\"select select-bordered bg-white border-gray-300 text-black text-sm focus:border-red-600 focus:ring-0\"><option disabled>Seleccionar...</option> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, s := range subjects {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(s)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/admin/adminClassModifyForm/adminClassModifyForm.templ`, Line: 57, Col: 23}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if class.Subject == s {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " selected")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, ">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(s)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/admin/adminClassModifyForm/adminClassModifyForm.templ`, Line: 57, Col: 62}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</select></div><!-- Descripción --><div class=\"flex flex-col md:col-span-2\"><label class=\"text-sm font-medium text-gray-700 mb-1\">Descripción</label> <textarea name=\"description\" rows=\"3\" class=\"textarea textarea-bordered bg-white border-gray-300 text-black text-sm focus:border-red-600 focus:ring-0\" required>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(class.Description)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/admin/adminClassModifyForm/adminClassModifyForm.templ`, Line: 69, Col: 24}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</textarea></div><!-- Grado --><div class=\"flex flex-col md:col-span-2\"><label class=\"text-sm font-medium text-gray-700 mb-1\">Grado</label> <select name=\"grade\" required class=\"select select-bordered bg-white border-gray-300 text-black text-sm focus:border-red-600 focus:ring-0\"><option disabled selected>Seleccionar grado...</option> <optgroup label=\"Primaria\"><option value=\"1primaria\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if class.Grade == "1primaria" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, ">1° de Primaria</option> <option value=\"2primaria\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if class.Grade == "2primaria" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, ">2° de Primaria</option> <option value=\"3primaria\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if class.Grade == "3primaria" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, ">3° de Primaria</option> <option value=\"4primaria\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if class.Grade == "4primaria" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, ">4° de Primaria</option> <option value=\"5primaria\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if class.Grade == "5primaria" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, ">5° de Primaria</option> <option value=\"6primaria\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if class.Grade == "6primaria" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, ">6° de Primaria</option></optgroup> <optgroup label=\"Secundaria\"><option value=\"1secundaria\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if class.Grade == "1secundaria" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, ">1° de Secundaria</option> <option value=\"2secundaria\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if class.Grade == "2secundaria" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, ">2° de Secundaria</option> <option value=\"3secundaria\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if class.Grade == "3secundaria" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, ">3° de Secundaria</option> <option value=\"4secundaria\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if class.Grade == "4secundaria" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, ">4° de Secundaria</option> <option value=\"5secundaria\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if class.Grade == "5secundaria" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, ">5° de Secundaria</option> <option value=\"6secundaria\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if class.Grade == "6secundaria" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, ">6° de Secundaria</option></optgroup></select></div><!-- Usuarios asignados --><div class=\"md:col-span-2 flex flex-col space-y-2 mt-2\"><label class=\"text-sm font-medium text-gray-700\">Usuarios asignados</label><div class=\"border border-gray-300 rounded-lg bg-white p-3 max-h-52 overflow-y-auto\"><template x-for=\"u in userList()\" :key=\"u.username\"><div class=\"flex justify-between items-center border-b border-gray-100 py-2 text-sm\"><div class=\"flex flex-col\"><a :href=\"`/admin/user/modify?username=${encodeURIComponent(u.username)}`\" class=\"text-black font-medium hover:text-red-600 hover:underline transition-colors\" x-text=\"u.username\"></a> <span class=\"text-gray-500 text-xs italic\" x-text=\"'Rol: ' + (u.role || 'Desconocido')\"></span></div><button type=\"button\" class=\"btn btn-xs\" :class=\"toDelete[u.username] ? 'bg-yellow-400 text-black' : 'bg-red-600 text-white hover:bg-red-700'\" x-text=\"toDelete[u.username] ? 'Restaurar' : 'Eliminar'\" @click=\"toDelete[u.username] ? restore(u.username) : markForDeletion(u.username)\"></button></div></template><template x-if=\"userList().length === 0\"><p class=\"text-gray-400 italic text-center py-2\">Sin usuarios</p></template></div><div class=\"flex items-center gap-3 pt-2\"><input type=\"text\" x-ref=\"newUsername\" class=\"input input-bordered bg-white border-gray-300 text-black text-sm w-44 focus:border-red-600 focus:ring-0 placeholder-gray-400\" placeholder=\"Nombre de usuario\"> <button type=\"button\" class=\"btn btn-sm bg-red-600 hover:bg-red-700 text-white text-sm\" @click=\"addUser($refs.newUsername.value)\">Agregar</button></div></div><!-- Submit --><div class=\"md:col-span-2 flex justify-end mt-6\"><button type=\"submit\" class=\"btn bg-red-600 hover:bg-red-700 text-white text-sm px-8\">Guardar Cambios</button></div></form><div id=\"class-edit-feedback\" class=\"text-sm text-gray-700\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
