// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package adminUserModify

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AdminUserModify() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"bg-white rounded-lg shadow-sm p-6 space-y-4\"><h2 class=\"text-xl font-semibold text-gray-800 mb-2\">Modificar Usuario</h2><p class=\"text-gray-600 text-sm mb-4\">Busca un usuario por su nombre de usuario para editar sus datos.</p><!-- Search User --><form hx-get=\"/admin/user/modify/search\" hx-target=\"#user-edit-form\" hx-swap=\"innerHTML\" class=\"flex gap-2 items-center\"><input type=\"text\" name=\"username\" placeholder=\"Nombre de usuario\" class=\"input input-bordered bg-white border-gray-300 text-gray-800 focus:border-red-400 focus:ring-1 focus:ring-red-400 text-sm flex-1\" required> <button type=\"submit\" class=\"btn bg-blue-600 text-white hover:bg-blue-700 text-sm\">Buscar</button></form><!-- Dynamic User Form --><div id=\"user-edit-form\" class=\"mt-6\"></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
