// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package adminAssetManager

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AdminAssetManager(subjects []string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"asset-manager-wrapper\" class=\"bg-white rounded-lg shadow-md border border-gray-200 p-6 space-y-6 animate-fade-in max-w-5xl mx-auto\"><!-- Header --><div class=\"flex items-center justify-between\"><h2 class=\"text-2xl font-semibold text-black tracking-tight\">Administrar recursos (PDFs)</h2><div class=\"flex items-center gap-3\"><span class=\"text-sm text-gray-500 italic\">Panel de administración</span> <button type=\"button\" class=\"btn btn-sm bg-yellow-500 hover:bg-yellow-600 text-black border-none shadow-sm\" @click=\"\n          const pwd = prompt('🔐 Ingrese la contraseña de administrador para continuar:');\n          if (!pwd) return;\n          if (pwd === 'otero2025') {\n            if (confirm('¿Está seguro? Esto volverá a cargar todos los recursos y puede generar costos.')) {\n              htmx.ajax('POST', '/admin/asset/refresh', {target:'#asset-list', swap:'innerHTML'});\n            }\n          } else {\n            alert('Contraseña incorrecta');\n          }\n        \">Refrescar Recursos</button></div></div><!-- Description --><p class=\"text-gray-600 text-sm\">Selecciona una materia y un grado para ver o subir los recursos PDF asociados.</p><!-- Filters --><form id=\"asset-filter-form\" hx-get=\"/admin/asset/manage/list\" hx-target=\"#asset-list\" hx-swap=\"innerHTML\" class=\"grid grid-cols-1 md:grid-cols-3 gap-4 items-end border border-gray-100 rounded-lg p-4\"><div class=\"flex flex-col\"><label class=\"text-sm text-gray-700 font-medium mb-1\">Materia</label> <select name=\"subject\" class=\"select select-bordered bg-white border-gray-300 text-sm text-black focus:border-red-600\"><option disabled selected>Seleccionar...</option> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, s := range subjects {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(s)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/admin/adminAssetManager/adminAsssetManager.templ`, Line: 53, Col: 27}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(s)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/admin/adminAssetManager/adminAsssetManager.templ`, Line: 53, Col: 33}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</select></div><div class=\"flex flex-col\"><label class=\"text-sm text-gray-700 font-medium mb-1\">Grado</label> <select name=\"grade\" class=\"select select-bordered bg-white border-gray-300 text-sm text-black focus:border-red-600\"><option disabled selected>Seleccionar...</option> <optgroup label=\"Primaria\"><option value=\"1primaria\">1°</option> <option value=\"2primaria\">2°</option> <option value=\"3primaria\">3°</option> <option value=\"4primaria\">4°</option> <option value=\"5primaria\">5°</option> <option value=\"6primaria\">6°</option></optgroup> <optgroup label=\"Secundaria\"><option value=\"1secundaria\">1°</option> <option value=\"2secundaria\">2°</option> <option value=\"3secundaria\">3°</option> <option value=\"4secundaria\">4°</option> <option value=\"5secundaria\">5°</option> <option value=\"6secundaria\">6°</option></optgroup></select></div><div class=\"flex justify-end md:col-span-1\"><button type=\"submit\" class=\"btn bg-red-600 hover:bg-red-700 text-white text-sm px-6 shadow-sm border-none h-10 w-full md:w-auto\">Buscar</button></div></form><!-- Existing Files Table --><div id=\"asset-list\" class=\"mt-6 border border-gray-200 rounded-lg bg-white p-4 text-sm text-gray-700\"><p class=\"text-gray-400 italic text-center\">Seleccione una materia y un grado.</p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
