// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package adminSubjectRename

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"encoding/json"
	"fmt"
)

func AdminSubjectRename(subjects []string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		subjectsJSONBytes, _ := json.Marshal(subjects)
		subjectsJSON := string(subjectsJSONBytes)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"subject-rename-wrapper\" x-data=\"renameManager()\" x-init=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf(`initExisting(%s)`, subjectsJSON))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/admin/adminSubjectRename/adminSubjectRename.templ`, Line: 14, Col: 59}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"bg-white rounded-lg shadow-md border border-gray-200 p-6 space-y-6 animate-fade-in max-w-3xl mx-auto\"><!-- Header --><div class=\"flex items-center justify-between\"><h2 class=\"text-2xl font-semibold text-black tracking-tight\">Renombrar materias</h2><span class=\"text-sm text-gray-500 italic\">Panel de administración</span></div><p class=\"text-gray-600 text-sm\">Cambia los nombres de las materias existentes. No se crearán ni eliminarán registros, solo se actualizarán los nombres.</p><!-- Form --><form id=\"subject-rename-form\" hx-post=\"/admin/subject/rename/update\" hx-target=\"#rename-feedback\" hx-swap=\"innerHTML\" hx-trigger=\"submit\" @submit=\"handleSubmit\" class=\"space-y-6\"><div class=\"overflow-x-auto\"><table class=\"table table-sm w-full border text-gray-800\"><thead><tr class=\"bg-gray-100 text-sm text-gray-700\"><th>#</th><th>Nombre actual</th><th>Nuevo nombre</th></tr></thead> <tbody><template x-for=\"(item, index) in renameList\" :key=\"item.old\"><tr class=\"hover:bg-gray-50 text-sm\"><td x-text=\"index + 1\" class=\"w-10 text-center\"></td><td x-text=\"item.old\" class=\"text-gray-800\"></td><td><input x-model=\"item.new\" type=\"text\" class=\"input input-sm bg-white border-gray-300 text-black text-sm w-full focus:border-red-600 focus:ring-0 placeholder-gray-400\" placeholder=\"Nuevo nombre\"></td></tr></template><template x-if=\"renameList.length === 0\"><tr><td colspan=\"3\" class=\"text-gray-400 italic text-center py-3\">No hay materias registradas</td></tr></template></tbody></table></div><!-- Submit --><div class=\"flex justify-end pt-4 border-t border-gray-100\"><button type=\"submit\" class=\"btn bg-green-600 hover:bg-green-700 text-white text-sm px-8\">Guardar cambios</button></div></form><!-- Feedback --><div id=\"rename-feedback\" class=\"text-sm text-gray-700\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
