// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package assignment

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AssignmentContent(subject string, assignments []Assignment) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"flex-1 px-6 py-8 flex gap-6\"><!-- Left: List of assignments --><aside class=\"w-1/3 bg-white border border-gray-200 shadow-sm rounded-lg p-4 overflow-y-auto\"><h2 class=\"text-md font-semibold text-gray-800 mb-3\">Asignaciones</h2><ul class=\"space-y-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, a := range assignments {
			templ_7745c5c3_Err = AssignmentSlot(a).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</ul></aside><!-- Right: Assignment details --><section class=\"flex-1 bg-white border border-gray-200 shadow-sm rounded-lg p-6\"><h2 class=\"text-xl font-semibold text-gray-900 mb-2\">Título de la asignación</h2><p class=\"text-gray-700 mb-4\">Aquí irá la descripción detallada de la asignación seleccionada.</p><!-- Upload placeholder (to be added later) --><div class=\"border border-dashed border-gray-300 rounded-md p-6 text-center text-gray-500\">Zona de entrega (se agregará funcionalidad más adelante)</div></section></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
