// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package adminClassCreate

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AdminCreateClass(subjects []string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"bg-white rounded-lg shadow-sm p-6 space-y-4\"><h2 class=\"text-xl font-semibold text-gray-800 mb-2\">Crear Clase</h2><p class=\"text-gray-600 text-sm mb-4\">Completa los datos de la nueva clase. El ID se asignará automáticamente.</p><form hx-post=\"/admin/class/create\" hx-target=\"#create-class-feedback\" hx-swap=\"outerHTML\" hx-on=\"htmx:afterSwap: this.reset()\" class=\"grid grid-cols-1 md:grid-cols-2 gap-4\"><!-- Nombre --><div class=\"form-control\"><label class=\"label\"><span class=\"label-text text-gray-700 font-medium\">Nombre</span></label> <input type=\"text\" name=\"name\" placeholder=\"Ej: Literatura 4°A\" class=\"input input-bordered bg-white border-gray-300 text-gray-800\n\t                 focus:border-red-400 focus:ring-1 focus:ring-red-400\n\t                 placeholder-gray-400 text-sm\" required></div><!-- Asignatura --><div class=\"form-control\"><label class=\"label\"><span class=\"label-text text-gray-700 font-medium\">Asignatura</span></label> <select name=\"subject\" class=\"select select-bordered bg-white border-gray-300 text-gray-800\n\t                 focus:border-red-400 focus:ring-1 focus:ring-red-400 text-sm\" required><option disabled selected>Seleccionar asignatura...</option> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, s := range subjects {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(s)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/admin/adminClassCreate/adminClassCreate.templ`, Line: 46, Col: 30}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(s)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/admin/adminClassCreate/adminClassCreate.templ`, Line: 46, Col: 36}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</select></div><!-- Descripción --><div class=\"form-control md:col-span-2\"><label class=\"label\"><span class=\"label-text text-gray-700 font-medium\">Descripción</span></label> <textarea name=\"description\" placeholder=\"Ej: Clase con el profe Hugo\" rows=\"3\" class=\"textarea textarea-bordered bg-white border-gray-300 text-gray-800\n\t                 focus:border-red-400 focus:ring-1 focus:ring-red-400\n\t                 placeholder-gray-400 text-sm\" required></textarea></div><!-- Grado --><div class=\"form-control md:col-span-2\"><label class=\"label\"><span class=\"label-text text-gray-700 font-medium\">Grado</span></label> <select name=\"grade\" class=\"select select-bordered bg-white border-gray-300 text-gray-800\n\t                 focus:border-red-400 focus:ring-1 focus:ring-red-400 text-sm\" required><option disabled selected>Seleccionar grado...</option> <optgroup label=\"Primaria\"><option value=\"1primaria\">1° de Primaria</option> <option value=\"2primaria\">2° de Primaria</option> <option value=\"3primaria\">3° de Primaria</option> <option value=\"4primaria\">4° de Primaria</option> <option value=\"5primaria\">5° de Primaria</option> <option value=\"6primaria\">6° de Primaria</option></optgroup> <optgroup label=\"Secundaria\"><option value=\"1secundaria\">1° de Secundaria</option> <option value=\"2secundaria\">2° de Secundaria</option> <option value=\"3secundaria\">3° de Secundaria</option> <option value=\"4secundaria\">4° de Secundaria</option> <option value=\"5secundaria\">5° de Secundaria</option> <option value=\"6secundaria\">6° de Secundaria</option></optgroup></select></div><!-- Botón --><div class=\"md:col-span-2 flex justify-end\"><button type=\"submit\" class=\"btn bg-red-600 text-white hover:bg-red-700 text-sm px-6\">Crear Clase</button></div></form><!-- Feedback --><div id=\"create-class-feedback\"></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
